package constants;

public class Strings {

    //Redis keys
    public static final String SID = "sid";
    public static final String NAME = "name";
    public static final String SERVICE = "service";
    public static final String CONFIG = "config";
    public static final String TOMCAT_BASE_PATH = "tomcatBasePath";
    public static final String ES_IP = "esIp";
    public static final String SIGN = "sign";
    public static final String ES_PORT = "esPort";

    public static final String SCAN_MEMPOOL = "scanMempool";
    public static final String SIGNER = "signer";
    public static final String TEMP = "temp";

    public static final String ES_PASSWORD_CIPHER = "esPasswordCipher";
    public static final String ORDER_LAST_HEIGHT = "orderLastHeight";
    public static final String FID_SESSION_NAME = "fidSessionName";
    public static final String ACCOUNT = "account";
    public static final String WAITER = "waiter";
    public static final String ORDER_LAST_BLOCK_ID = "orderLastBlockId";
    public static final String BEST_HEIGHT = "bestHeight";
    public static final String HEIGHT = "height";
    public static final String DESC = "desc";
    public static final String ASC = "asc";
    public static final String N_PRICE = "nPrice";
    public static final String PRICE = "price";
    public static final String IS_PRICE_PER_REQUEST = "isPricePerRequest";

    public static final String BEST_BLOCK_ID = "bestBlockId";
    public static final String WINDOW_TIME = "windowTime";
    public static final String CHECK_ORDER_OPRETURN = "checkOrderOpReturn";
    public static final String AVATAR_ELEMENTS_PATH = "avatarElementsPath";
    public static final String AVATAR_PNG_PATH = "avatarPngPath";
    public static final String CONFIG_FILE_PATH = "configFilePath";
    public static final String LOCAL_DATA_PATH = "localDataPath";
    public static final String CONSUME_VIA = "consumeVia";
    public static final String ORDER_VIA = "orderVia";
    public static final String UNPAID_COST = "unpaidCost";
    public static final String REWARD_PENDING_MAP = "rewardPendingMap";
    public static final String FROM_FID = "fromFid";
    public static final String PUBLIC = "public";
    public static final String FID = "fid";
    public static final String SERVICE_NAME = "serviceName";
//    public static final String PARAMS_ON_CHAIN = "paramsOnChain";
    public static final String OPRETURN = "opreturn";
    public static final String CURRENCY = "currency";
    public static final String URL_HEAD = "urlHead";

    public static final String MIN_PAYMENT = "minPayment";
    public static final String SESSION_DAYS = "sessionDays";
    public static final String SESSION_KEY = "sessionKey";
    public static final String PRICE_PER_K_BYTES = "pricePerKBytes";
    public static final String PRICE_PER_K_BYTES_CARVE = "pricePerKBytesCarve";
    public static final String PRICE_PER_REQUEST = "pricePerRequest";
    public static final String BALANCE = "balance";
    public static final String REWARD = "reward";
    public static final String LAST_REWARD = "last_reward";
    public static final String WEBHOOK = "webhook";
    public static final String REWARD_ID = "rewardId";

    public static final String ANY_KEY = "Any key to continue...";
    public static final String BUILDER_SHARE_MAP = "builderShareMap";
    public static final String CONSUME_VIA_SHARE = "consumeViaShare";
    public static final String ORDER_VIA_SHARE = "orderViaShare";
    public static final String COST_MAP = "costMap";
    public static final String STATE = "state";
    public static final String UNPAID = "unpaid";
    public static final String TIME = "time";

    public static final String OP_RETURN_FILE_PATH = "opReturnFilePath";
    public static final String LISTEN_PATH = "listenPath";
    public static final String FIELDS = "fields";
    public static final String SESSION_NAME = "sessionName";
    public static final String VIA = "via";
    public static final String TYPE = "type";
    public static final String CLOSED = "closed";
    public static final String ACTIVE = "active";
    public static final String TYPES = "types";
    public static final String HOOK_USER_ID = "hookUserId";
    public static final String HOOK_LAST_HEIGHT = "hookUserId";
    public static final String ENDPOINT = "endpoint";
    public static final String TARGET_API = "targetApi";
    public static final String HOOK_INFO = "hookInfo";

    public static final String FCH = "fch";
    public static final String AGAIN = "again";
    public static final String WEBHOOK_ENDPOINT_SESSION_KEY = "webhookEndpointSessionKey";
    public static final String DOT_JSON = ".json";
    public static final String DOCS = "docs";
    public static final String BIRTH_HEIGHT = "birthHeight";
    public static final String ORDER = "order";
    public static final String NONCE = "nonce";
    public static final String RENEW = "renew";
    public static final String SUBSCRIBE = "subscribe";
    public static final String UNSUBSCRIBE = "unsubscribe";
    public static final String OP = "op";
    public static final String ERROR = "error";
    public static final String PARAMS = "params";
    public static final String UNSIGNED_TX_FOR_CS = "unsignedTxForCs";
    public static final String IGNORE = "ignore";
    public static final String INIT_SYM_KEY_CIPHER = "initSymKeyCipher";
    public static final String SYM_KEY_CIPHER = "symKeyCipher";
    public static final String WEB_PARAMS = "webParams";
    public static final String API = "api";
    public static final String USER_ID = "userId";
    public static final String CHECK = "check";
    public static final String FOUND = "found";
    public static final String PRE_KEY = "priKey";
    public static final String SWAP = "swap";
    public static final String REFUND = "refund";
    public static final String WITHDRAW = "withdraw";
    public static final String HIST = "hist";
    public static final String MONEY = "money";
    public static final String DOGE = "doge";
    public static final String BTC = "btc";
    public static final String BCH = "bch";
    public static final String LTC = "ltc";
    public static final String XEC = "xec";
    public static final String LP = "lp";
    public static final String SETTINGS = "settings";
    public static final String DATA_LIFE_DAYS = "dataLifeDays";
    public static final String DATA = "data";
    public static final String ES_ACCOUNT_ID = "esProviderId";
    public static String spendCashMapKey = "spentCashMap";
    public static String newCashMapKey = "newCashMap";
}
